---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: main
    jkube.io/git-url: https://github.com/robinroos/jkube-513.git
    app.openshift.io/vcs-uri: https://github.com/robinroos/jkube-513.git
    jkube.io/git-commit: 3ca6a1db46d65e5145abb34d0d8376b33710d42f
    jkube.io/git-branch: main
    jkube.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot
    jkube.io/scm-tag: HEAD
    prometheus.io/path: /metrics
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    app: spring-boot
    provider: jkube
    version: 1.0.1
    group: org.eclipse.jkube.quickstarts.maven
  name: spring-boot
  namespace: cacheui
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - port: 5701
    protocol: TCP
    targetPort: 5701
  selector:
    app: spring-boot
    provider: jkube
    group: org.eclipse.jkube.quickstarts.maven
  type: ClusterIP
